spring.application.name=CafeAromaESabor

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/CafeAromaESabor?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Senai@2024

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# THYMELEAF
spring.thymeleaf.cache=false